### ISSUE TITLE
Scope of pointer, reference, etc. types

### ISSUE THREAD

**Issue by matus-chochlik** [matus-chochlik/std_cpp_refl#5]
What is the scope of native types, CV-qualified types, pointer, reference, array, function, etc. types, like: `const std::string* const * [5]`?

Are all types scope members -- are all metaobjects reflecting types conforming to `meta::ScopeMember` ?

A) The scope of such types is the global scope:

```
using MetaT = reflexpr(const std::string* const * [5]);
static_assert(meta::ScopeMember<MetaT>, "");
static_assert(meta::GlobalScope<meta::get_scope_m<MetaT>>, "");
```

B) Such types don't have any scope -- metaobjects reflecting them are not `meta::ScopeMember`s.

```
using MetaT = reflexpr(const std::string* const * [5]);
static_assert(!meta::ScopeMember<MetaT>, "");
meta::get_scope_m<MetaT> // ill-formed
```

---

What about native types?

```
using MetaT = reflexpr(int);
meta::ScopeMember<MetaT> // true / false ?
meta::GlobalScope<meta::get_scope_m<MetaT>> // is this valid ?
```

**Comment by ricardofandrade** [comment]
I'd argue that B) is the correct interpretation for these types.
- First, ::int, ::int*, ::int[N] are not possible, so A) would be misleading in case someone uses it to determine the scope. In the following example, reifying the namespace and type would fail for "int":
  
  <pre><code>
  auto et = erased_type{}; // such as std::any
  if constexpr (meta::GlobalScope&ltMetaNamespace&gt) {
      et = ::unreflexpr(MetaInt){};
  } else {
      et = unreflexpr(MetaNamespace)::unreflexpr(MetaInt){};
  }
  </code></pre>
  
  While with B):
  
  <pre><code>
  auto i = erased_type{};
  if constexpr (meta::ScopeMember&ltMetaInt&gt) {
      if constexpr (meta::GlobalScope&ltMetaNamespace&gt) {
          et = ::unreflexpr(MetaInt){};
      } else{
          et = unreflexpr(MetaNamespace)::unreflexpr(MetaInt){};
      }
  } else {
      et = unreflexpr(MetaInt){};
  }
  </code></pre>
- Second, most of these are types are original from C where the notion of namespaces doesn't exist.
  So, it seems natural IMHO that such types don't have a scope.

If someone want a built-in to have a namespace, an alias is the way.

**Comment by matus-chochlik** [comment]
Resolved as B) -- such types don't have a scope.
